// src/app/articles/page.tsx
import React from "react";
import Link from "next/link";
import { BookOpen, Calendar, User, ArrowRight, Sparkles, Mail } from "lucide-react";
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "@/components/ui/card";
import { Newsletter } from "@/components/Newsletter";

export default function ArticlesPage() {
  const articles = [
    {
      slug: "ai-avatars-and-email",
      title: "AI Avatars and Email, the Killer App of the AI Age is Here",
      author: "Joe Terry, Head DG",
      date: "2024-12-09",
      category: "AI Engineering & Email Avatars",
      description:
        "AI Avatars paired with automated email workflows transform client engagement and follow-up. But what can they really do for your business?",
    },
    {
      slug: "ai-powered-workflow",
      title: "Building an AI-Powered Development Workflow",
      author: "Derivative Genius Engineering Team",
      date: "2023-12-12",
      category: "AI Web Development",
      description:
        "Learn how to integrate modern AI tools, agentic workflows, and Next.js 16 into your development pipeline for enhanced productivity and code quality.",
    },
  ];

  return (
    <div className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8 space-y-16">
      <div className="text-center max-w-3xl mx-auto space-y-4">
        <div className="mx-auto inline-flex items-center space-x-2 rounded-full border border-blue-500/30 bg-blue-500/10 px-4 py-1.5 text-xs font-semibold text-blue-400">
          <BookOpen className="h-3.5 w-3.5" />
          <span>Derivative Insights & Articles</span>
        </div>
        <h1 className="text-4xl font-extrabold tracking-tight text-white sm:text-5xl">
          Articles & AI Engineering Insights
        </h1>
        <p className="text-lg text-slate-300">
          Perspectives on AI web development, autonomous agents, AI Avatars, and full-stack software architecture.
        </p>
      </div>

      <div className="grid grid-cols-1 gap-8 md:grid-cols-2">
        {articles.map((art, idx) => (
          <Card key={idx} className="flex flex-col justify-between border-slate-800 bg-slate-900/90 shadow-xl backdrop-blur-xl">
            <CardHeader>
              <div className="flex items-center justify-between">
                <span className="rounded-full bg-slate-800 px-3 py-1 text-xs font-medium text-blue-400">
                  {art.category}
                </span>
                <div className="flex items-center space-x-1.5 text-xs text-slate-400">
                  <Calendar className="h-3.5 w-3.5" />
                  <span>{art.date}</span>
                </div>
              </div>
              <CardTitle className="mt-4 text-2xl text-white hover:text-blue-400 transition-colors">
                <Link href={`/articles/${art.slug}`}>{art.title}</Link>
              </CardTitle>
              <div className="flex items-center space-x-2 text-xs font-medium text-slate-400 mt-2">
                <User className="h-3.5 w-3.5 text-blue-400" />
                <span>{art.author}</span>
              </div>
              <CardDescription className="mt-3 text-sm text-slate-300 leading-relaxed">
                {art.description}
              </CardDescription>
            </CardHeader>
            <CardContent className="pt-2">
              <Link
                href={`/articles/${art.slug}`}
                className="inline-flex items-center space-x-2 text-xs font-semibold text-blue-400 hover:text-blue-300"
              >
                <span>Read Full Article</span>
                <ArrowRight className="h-3.5 w-3.5" />
              </Link>
            </CardContent>
          </Card>
        ))}
      </div>

      <Newsletter />
    </div>
  );
}

// src/views/Articles.vue
<template>
  <div class="min-h-screen bg-white py-16">
    <div class="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
      <div class="relative">
        <div class="lg:text-center mb-12">
          <h2 class="text-base text-indigo-600 font-semibold tracking-wide uppercase">Derivative Insights</h2>
          <p class="mt-1 text-3xl leading-8 font-extrabold tracking-tight text-gray-900 sm:text-4xl">
            Latest Articles
          </p>
          <p class="mt-2 max-w-2xl text-lg text-gray-500 lg:mx-auto">
            Exploring the intersection of AI, automation, and software engineering through in-depth technical articles.
          </p>
        </div>

        <div class="grid gap-12 md:grid-cols-2">
          <article 
            v-for="article in articles" 
            :key="article.title" 
            class="group bg-white rounded-lg shadow-sm hover:shadow-md transition-all duration-300"
          >
            <div class="relative">
              <div class="relative h-56 w-full overflow-hidden rounded-t-lg">
                <img 
                  :src="article.imageUrl" 
                  :alt="article.title" 
                  class="h-full w-full object-cover object-center"
                >
              </div>
              <div class="p-8">
                <div class="flex items-center gap-x-4 text-sm mb-4">
                  <time :datetime="article.datetime" class="text-gray-500">{{ article.date }}</time>
                  <span class="relative z-10 rounded-full bg-gray-100 px-3 py-1.5 font-medium text-gray-600">
                    {{ article.category }}
                  </span>
                </div>
                <div class="group relative">
                  <h3 class="text-xl font-semibold leading-7 text-gray-900 group-hover:text-indigo-600">
                    <a :href="article.href">
                      <span class="absolute inset-0"></span>
                      {{ article.title }}
                    </a>
                  </h3>
                  <p class="mt-4 text-base text-gray-600 leading-6">{{ article.description }}</p>
                </div>
              </div>
            </div>
          </article>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup name="ArticlesPage">
import { ref } from 'vue'

const articles = ref([
  {
    title: "Building an AI-Powered Development Workflow",
    description: "Explore how to integrate modern AI tools into your development pipeline. From code generation to automated testing, learn how AI can enhance your software engineering process.",
    href: "/articles/ai-powered-development-workflow",
    date: "Dec 12, 2023",
    datetime: "2023-12-12",
    category: "AI Engineering",
    imageUrl: "/images/articles/ai-automation.jpg"
  }
])
</script>

<style scoped>
</style>
